#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="imagine.css" />
#+OPTIONS: toc:nil num:nil html-style:nil
#+HTML_HEAD: <base target="_blank">

#+Title: Senthil Kumaran's Projects

* Software
** LearnToSolveIt                                             :c:python:docs:
*** https://www.learntosolveit.com/
This was my first project, aimed to help me learn C programming language. It has
survived for 20 years, and I have been updating it periodically. I have to
finish this with the C Code with proper understanding.

** CPython                                                    :python:ci:git:
*** https://github.com/python/cpython/pulls/orsenthil
*** https://buildbot.python.org/all/#/workers/43
I am a Cpython hacker. I got involved during Python2 to Python3 development. I
contributed to urllib, and urlparse modules. I also contributed to migration of
python repo from mercurial to git.

** Eksctl-Explorer                                               :kubernetes:
*** https://eksctl.learntosolveit.com/
Website to explore eksctl setup commands. It provides the manifest examples that
be used directly.

** Fortune Browser Extension :javascript:python:datastore:
*** https://github.com/orsenthil/fortune-browser-extension
It is my collection of quotes that is displayed with a new browser tabs. I
enjoy reading them, and adding to the collection.


** Blog                                              :python:nikola:
*** https://senthil.learntosolveit.com/
My blog is built with Python Nikola Framework, it has technical articles,
opinions on politics, self-help and my reviews on books.

** Minecraft Server                                        :minecraft:docker:
*** https://mc.learntosolveit.com/
We host a minecraft server, called Occamy Minecraft Server. My children build
some amazing creations in the minecraft.

** Mastodon                                                          :docker:
*** https://social.learntosolveit.com/home
I host a Mastodon instance for myself. It is a microblogging service, federated
universe where you can follow people from other instances and exchange amazing
ideas.


** Courses Documentation                                      :python:sphinx:
*** https://courses.learntosolveit.com/
I have taken extensive notes, and maintained them during various classes I have
taken online. This is helpful to many students. The website also consists of my
notes from Georgia Tech OMSCS course.

** Private Trading Application                                       :python:
*** https://github.com/orsenthil/trading
I employ some options trading strategies to derive benefits. I have written code
to automate trading. This is for single person, personal use only.

** Kubectl Explorer                                              :javascript:
*** https://kubectl.learntosolveit.com/
Website to explore kubectl commands. It provides the manifest examples that can
be used directly.

** Marriage Website                                        :python:appengine:
*** https://shalini-weds-senthil.appspot.com/MainPage
As a true hacker, I created a website for my marriage and hosted it in Google
AppEngine. You will to love the quotes on marriage that I and my wife collected.
The guest form has wishes collected from our friends.

** Discipline Score :python:appengine:
*** http://discipline-score.appspot.com/

This is a todo list application that I built for myself. This application was
built as my effort to keep track and improve my self-discipline.

Along with the todo, I give a rating for evey task, and score it after I
complete it. The task are time bound.

The rating helps me priorize the task, and score is a self-reflection of my
performance on the task. The application will give a score (discipline-score)
for my effort.

My goal with this application was to track and maximize my discipline score.
This application helped me. It was helpful because it was longest todo
application I struck with.

** Bitcoin                                                          :bitcoin:
I have bitcoin miner running at host in US. I like the domain of cryptocurrency.

** Rapple                                                      :opensource:c:
*** https://rapple.sourceforge.net/index.html
This was my first volunteering contribution to an Open Source project.

* Sourashtra Language

** Yummy Sourashtra
*** https://yummysourashtra.com/

** thinnal.org
*** https://thinnal.org

This is community website for Sourashtra language Speakers. More than 1000
members use this website. This has lead to many offshoot, standalone projects in
the community, and helped in growth of the local community.

** Sourashtra Language in Memrise
*** https://app.memrise.com/course/5916249/sourashtra/

** Yummy Sourashtra Book 1
My dad wrote a cook book consisting of various Sourashtra Recipes.

** Yummy Sourashtra Book 2
My dad wrote a cook book consisting of various Sourashtra Recipes.

** Sourashtra  - Havard Kyoto Transliteration Scheme
It is a transliteration scheme used for spoken Sourashtra language to writen
using latin script.

* Jobs

*** Amazon Web Services

I work as a Senior Systems Development Engineer in the Amazon Web Services in
the Elastic Kubernetes Service. I focus on the Container Networking domain, and
work on projects, services related to Container Networks, like VPC CNI,
Resource Controller,Kube-Proxy, CoreDNS and Load Balancer Controller.

I wrote an important service to detect security vulnerablities early for the
EKS services.

*** Mesosphere / D2IQ

As a Staff Software Engineer and Tech Lead in the Developer
Productivity Team at D2IQ, my responsiblities include design and
development of software tools to improve the software development
experience at D2IQ.  It includes designing, and developing Continous
Integration systems and jobs that are used for testing Distributed
System Software.

My job duties also includes mentoring junior developers, reviewing the
design and code.

*** Okta

As a Senior Software Engineer in the Developer Productivity team at
Okta, my job included developing Test Automation Systems using Java
Programming language. My job responsibilities included developing a
custom developed continous integration framework in Java, using
Dropwizard.io framework and JQuery Javascript Framework. We employed
technologies like Bash scripting, Docker, Amazon Elastic Container
Service to develop the Test Automation system.

I wrote a tool to do automated deployments using software tool called
Ansible in Python programming language. As a senior engineer, my
responsibilities include reviewing code written by other engineers in
the team.

*** Twitter

Write Release and Deployment tool used for Deploying
Twitter.com. Develop BUILD tool called Pants, which uses Python
programming language and ability to build multiple software
packages. Develop git porcelain to ease the development workflow of
engineers within Twitter. Review code written by others. Design
discussions of new products for use within Twitter. Work on technical
and algorithmic aspects of large systems while assessing systems
ability to meet team members needs. Work closely with, and incorporate
feedback from, engineers from other teams at Twitter, product
management, and interaction designers. Work on the scalability,
resilience, and efficiency of backend components. Build storage
systems, libraries, and frameworks.


*** Lucasfilm Singapore

I worked as a Senior Software Engineer in the Information Systems team and
worked on web application that was used in movie production pipelie. The web
application was a Python web application using Pyramid framework. extensively
used Javascript, JQuery and backed was an Oracle Database.

*** Akamai
Akamai – March 2, 2009 – January 31, 2011

I was working as a Senior Software Engineer in the Akamai. I developed a tool
called Toolserver that used to gather logs from various services and pushed to
the mapreduce processing system. Toolserver was developed using Twisted
asynchronous Python framework.

*** Dell India
I was working as a Software Engineer in Dell India R&D Center, Bangalore. I
worked in the Dell OpenManage Server Administrator team. I was responsible for
developing the software that is used to manage the Dell Servers.


* Patents

*** System and Method For Downloading Content Associated with Optical
Media US 12/342,732 · Filed Dec 23, 2008

Fast Download like mechanism for downloading content in your setup box and Blu
Ray disk.

*** System and Method for Audiovisual Content Search
US 11/671,535 · Filed Feb 6, 2007

A subtitle indexing engine and ability search by dialogues for the movies that
you are watching on Blu Ray disc.


*** System and method for printer-based syndication
US 11/087,966  Filed Mar 23, 2005

Idea for RSS support with printer firmware so that customized newspapers can be
scheduled for delivery morning to your house.

*** Obtaining user input for inclusion in system management logs
US 11/008,443 · Filed Dec 9, 2004

Idea to include log messages written by system administrators with System log
generated by services.
